# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact_details.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontact_details.proto\"=\n\x0bPhoneNumber\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.PhoneNumberType\x12\x0e\n\x06number\x18\x02 \x01(\t\"T\n\x16\x41lternativeContactInfo\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.AlternativeContactType\x12\x13\n\x0bscreen_name\x18\x02 \x01(\t\"}\n\x0e\x43ontactDetails\x12\x1d\n\x07numbers\x18\x01 \x03(\x0b\x32\x0c.PhoneNumber\x12<\n\x1b\x61lternative_contact_methods\x18\x02 \x03(\x0b\x32\x17.AlternativeContactInfo\x12\x0e\n\x06\x65mails\x18\x03 \x03(\t*H\n\x0fPhoneNumberType\x12\x17\n\x13UNKNOWN_NUMBER_TYPE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04\x43\x45LL\x10\x02\x12\x08\n\x04WORK\x10\x03*s\n\x16\x41lternativeContactType\x12\x18\n\x14UNKNOWN_CONTACT_TYPE\x10\x00\x12\x16\n\x12\x46\x41\x43\x45\x42OOK_MESSENGER\x10\x01\x12\r\n\tINSTAGRAM\x10\x02\x12\x0b\n\x07TWITTER\x10\x03\x12\x0b\n\x07\x44ISCORD\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contact_details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHONENUMBERTYPE']._serialized_start=301
  _globals['_PHONENUMBERTYPE']._serialized_end=373
  _globals['_ALTERNATIVECONTACTTYPE']._serialized_start=375
  _globals['_ALTERNATIVECONTACTTYPE']._serialized_end=490
  _globals['_PHONENUMBER']._serialized_start=25
  _globals['_PHONENUMBER']._serialized_end=86
  _globals['_ALTERNATIVECONTACTINFO']._serialized_start=88
  _globals['_ALTERNATIVECONTACTINFO']._serialized_end=172
  _globals['_CONTACTDETAILS']._serialized_start=174
  _globals['_CONTACTDETAILS']._serialized_end=299
# @@protoc_insertion_point(module_scope)
