# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pantry.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpantry.proto\"{\n\nPantryItem\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.PantryItemType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x15\n\rdate_acquired\x18\x04 \x01(\x03\x12\x17\n\x0f\x65xpiration_date\x18\x05 \x01(\x03\"$\n\x06Pantry\x12\x1a\n\x05items\x18\x01 \x03(\x0b\x32\x0b.PantryItem*x\n\x0ePantryItemType\x12\x15\n\x11UNKNOWN_ITEM_TYPE\x10\x00\x12\x0b\n\x07PROTEIN\x10\x01\x12\r\n\tVEGETABLE\x10\x02\x12\t\n\x05\x46RUIT\x10\x03\x12\t\n\x05\x44\x41IRY\x10\x04\x12\t\n\x05SPICE\x10\x05\x12\t\n\x05GRAIN\x10\x06\x12\x07\n\x03OIL\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pantry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PANTRYITEMTYPE']._serialized_start=179
  _globals['_PANTRYITEMTYPE']._serialized_end=299
  _globals['_PANTRYITEM']._serialized_start=16
  _globals['_PANTRYITEM']._serialized_end=139
  _globals['_PANTRY']._serialized_start=141
  _globals['_PANTRY']._serialized_end=177
# @@protoc_insertion_point(module_scope)
