# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pantry_pb2 as pantry__pb2
import contact_details_pb2 as contact__details__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x0cpantry.proto\x1a\x15\x63ontact_details.proto\"6\n\x04Name\x12\r\n\x05\x66irst\x18\x01 \x01(\t\x12\x0c\n\x04last\x18\x02 \x01(\t\x12\x11\n\tpreferred\x18\x03 \x01(\t\"z\n\x07\x41\x64\x64ress\x12\x0f\n\x07street1\x18\x01 \x01(\t\x12\x0f\n\x07street2\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0b\n\x03zip\x18\x05 \x01(\t\x12\x10\n\x08latitude\x18\x06 \x01(\x01\x12\x11\n\tlongitude\x18\x07 \x01(\x01\"y\n\x0bUserDetails\x12\x13\n\x04name\x18\x01 \x01(\x0b\x32\x05.Name\x12(\n\x0f\x63ontact_details\x18\x02 \x01(\x0b\x32\x0f.ContactDetails\x12\x19\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x08.Address\x12\x10\n\x08pronouns\x18\x04 \x01(\t\"Q\n\x04User\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\"\n\x0cuser_details\x18\x02 \x01(\x0b\x32\x0c.UserDetails\x12\x17\n\x06pantry\x18\x03 \x01(\x0b\x32\x07.Pantryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAME']._serialized_start=51
  _globals['_NAME']._serialized_end=105
  _globals['_ADDRESS']._serialized_start=107
  _globals['_ADDRESS']._serialized_end=229
  _globals['_USERDETAILS']._serialized_start=231
  _globals['_USERDETAILS']._serialized_end=352
  _globals['_USER']._serialized_start=354
  _globals['_USER']._serialized_end=435
# @@protoc_insertion_point(module_scope)
